source 'https://rubygems.org'

gem 'capistrano', '~> 3.2.0'
gem 'capistrano-composer'
gem 'breakpoint'
gem 'sassy-buttons'
gem 'compass-normalize'
gem 'sass', '>= 3.3'
gem 'compass', '~> 1.0.0.rc.1'
gem 'sass-globbing', '~> 1.1.1'