name: PHP

on: [push, pull_request]

env:
  PHPCS_DIR: /tmp/phpcs
  PHPCOMPAT_DIR: /tmp/phpcompatibility
  SNIFFS_DIR: /tmp/sniffs
  WPCS_DIR: /tmp/wpcs
  COMPOSER_AUTH: '{"github-oauth": {"github.com": "${{ secrets.GITHUB_TOKEN }}"}}'

jobs:
  build:
    name: Test php
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Setup PHP with Xdebug 2.x
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        coverage: xdebug2

    - name: Set up PHPCS and WordPress-Coding-Standards
      uses: php-actions/composer@v6
      env:
        COMPOSER: "composer.json"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        php_version: "8.3"
        version: "2.3.7"
        args: "--ignore-platform-reqs --optimize-autoloader"

    - name: Run PHP_CodeSniffer
      run: |
        vendor/bin/phpcs -p . --extensions=php --ignore=vendor,content/themes,content/plugins,content/uploads,node_modules,src,js,css,sass,plugin-update-checker,wp,mu-plugins/air-blocks-acf-example-data,content/languages --standard=phpcs.xml

    - name: Test PHP for syntax errors
      run: find -L . -name '*.php' -not -path "./vendor/*" -not -path "./node_modules/*" -not -path "./src/*" -not -path "./js/*" -not -path "./css/*" -not -path "./sass/*" -not -path "./plugin-update-checker/*" -print0 | xargs -0 -n 1 -P 4 php -l
